### ISSUE TITLE
Update Plugin for Webpack 5

### ISSUE THREAD

**Issue by vquigley** [johnagan/crx-webpack-plugin#19]
Plugin is not compatible with Webpack 5. Get the following error:

[webpack-cli] TypeError: compiler.plugin is not a function
    at Plugin.apply (C:\project\src\node_modules\crx-webpack-plugin\index.js:42:19)
    at createCompiler (C:\project\src\node_modules\webpack\lib\webpack.js:74:12)
    at create (C:\project\src\node_modules\webpack\lib\webpack.js:127:16)
    at webpack (C:\project\src\node_modules\webpack\lib\webpack.js:135:47)
    at WebpackCLI.f [as webpack] (C:\project\src\node_modules\webpack\lib\index.js:55:16)
    at WebpackCLI.createCompiler (C:\project\src\node_modules\webpack-cli\lib\webpack-cli.js:2053:29)
    at async WebpackCLI.buildCommand (C:\project\src\node_modules\webpack-cli\lib\webpack-cli.js:2173:20)
    at async Command.<anonymous> (C:\project\src\node_modules\webpack-cli\lib\webpack-cli.js:850:25)
    at async Promise.all (index 1)
    at async Command.<anonymous> (C:\project\src\node_modules\webpack-cli\lib\webpack-cli.js:1495:13)

**Comment by ilyadonskoy** [comment]
Hi! Any updates? Need it. Thx.

I think we have to create another plugin with supports webpack 5. Creating a fork with your fix should be a good idea
